version: '3'
services:
  sightplusplus-orgserver:
    image: orgserver.azurecr.io/orgserver
    restart: always
    build: .
    ports:
      - '5000:5000'
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'